### PR TITLE
fix expo config plugin

### PR DESCRIPTION
**Pull request by ottob**
But there is still an error:
```
Error: Cannot find module '../../package.json'
Require stack:
- /myproject/node_modules/@intercom/intercom-react-native/lib/commonjs/expo-plugins/index.js
```

since
https://github.com/intercom/intercom-react-native/blob/f75b38cdf9e4c43b8bb35fee98803920cf7518c0/src/expo-plugins/index.ts#L19
should be
```js
import packageJson from '../../../package.json';
```
because after the build the file ends up in /lib/commonjs/expo-plugins/index.js so it needs to step back three folders.
not sure how to fix that...

### CODE REVIEW

**Comment by ansh** [comment]
Yeah this is broken and should be merged ASAP @uddish

**Comment by tomfinney** [comment]
the only way i can to make this work is to just completely remove importing the package.json from inside of the plugin file. 

`import packageJson from '../../package.json';`

we just can't have a relative import like that if `src/expo-plugins/index.ts` is going to end up nested in another directory

so, my great suggestion would just remove import package.json, at the bottom of the `expo-plugins/index.ts` file, change it to be like

```
const thing = (pkg) => createRunOncePlugin(
  withIntercomReactNative,
  pkg.name,
  pkg.version
);

export default thing
```

then in side of the `app.plugin.js` file, we import the package json inside of there and pass the stuff along like

```
const packageJson = require('./package.json');

const pkg = {
  // Prevent this plugin from being run more than once.
  // This pattern enables users to safely migrate off of this
  // out-of-tree `@config-plugins/intercom-react-native` to a future
  // upstream plugin in `intercom-react-native`
  name: packageJson.name,
  // Indicates that this plugin is dangerously linked to a module,
  // and might not work with the latest version of that module.
  version: packageJson.version,
};

const plugin = require('./lib/commonjs/expo-plugins');

module.exports = plugin.default(pkg);
```

**Comment by ottob** [comment]
> the only way i can think to make this work (quickly...) is to just completely remove importing the package.json from inside of the expo plugins file.

Thanks, this sounds like a good solution. I tried to push commits for this now.

**Comment by tomfinney** [comment]
> > the only way i can think to make this work (quickly...) is to just completely remove importing the package.json from inside of the expo plugins file.
> 
> Thanks, this sounds like a good solution. I tried to push commits for this now.

👏 

seems alright to me

there's probably a less dumb way of doing it but the `app.plugin.js` file itself referring to a lib/commonjs file that only exists after being built makes it a bit tricky... 🤷

**Comment by renatoalvesmh** [comment]
Could we merge it ? im having issues with sdk 50

**Comment by renatoalvesmh** [comment]
@ottob seems is failing on lint step in CI
just an small fix, would be possible to merge it ?
We are having issues in our company with new version would be amazing if its could be merged

**Comment by renatoalvesmh** [comment]
@ottob thank you so much
just missing to merge and commit new version in npm

**Comment by renatoalvesmh** [comment]
Hello
@ottob @uddish any plans to release it ?
Thanks

**Comment by CarlMenke** [comment]
My boss is waiting for a feature in our app that wont work until this is merged, you guys are life savers if you can get it merged today or tomorrow!

**Comment by uddish** [comment]
Hey @ottob 
Thanks for the PR. Were you able to test it locally?

**Comment by renatoalvesmh** [comment]
@uddish @ottob Thank you! Would be great if it can be released

**Review by MikeMcNamara — APPROVED** [review]
Looks good! Thanks for your work on this folks. Will get this merged in now.

**Comment by renatoalvesmh** [comment]
Thank you so much @MikeMcNamara 
Some plans to bump version in npm ?

**Comment by MikeMcNamara** [comment]
Version has been bumped now in npm!

**Comment by renatoalvesmh** [comment]
https://www.npmjs.com/package/@intercom/intercom-react-native
still not in npm

**Comment by renatoalvesmh** [comment]
@MikeMcNamara

**Comment by hanyufoodles** [comment]
I just tested the plugin with 6.8.0 and it works! I had just to replace `config-plugin-react-native-intercom` by `@intercom/intercom-react-native`.

Thank you all for your work! ❤️  we can finally to switch to an official up-to-date plugin!

**Comment by ottob** [comment]
@MikeMcNamara two steps forward, one step back 😀

#171

**Comment by jamesedmonston** [comment]
Thanks for this!

**Pull request merged**
