### PR TITLE
updating android to sdk 12.1.1

### PR DESCRIPTION
**Pull request by niamh-coleman**

### CODE REVIEW

**Review by github-management-service — COMMENTED** [review]
👋 Hey there,
It looks like your PR introduces some terminology we are trying to phase out of our codebase.
For each of the following files, we ask that you update the usage according to the [TRU Program Plan](https://docs.google.com/document/d/1IQoe6vQfGq03NiCMYhxdx2NBesgA0jcJe5ZYgMLyDSQ/edit?usp=sharing).


* example/metro.config.js, line number(s): 2


While this check doesn't block 🚢-ing, please consider making the following suggested terminology changes:
Old Usage | Updated Usage
-- | --
Whitelist (verb) | Trust
Blacklist (verb) | Block
Whitelist (noun) | Trusted list
Blacklist (noun) | Blocked list
Master (DB node) | Primary
Slave (replicated DB node) | Replica
Slave (non-replicated DB node) | Secondary




Feel free to reach out to [#tru-working-group](https://intercom.slack.com/archives/C015WCE1UQ1) with any questions.
Let me know what you end up doing after reading this:

* [ ] I addressed this comment, it’s fixed now
* [ ] I will fix in a subsequent PR
* [x] I will keep the files as-is

**Review by SanthoshKumarSrikanthaMurali — APPROVED** [review]

**Review by prithivraj — APPROVED** [review]

**Comment by armouti** [comment]
Hello @niamh-coleman this last update `3.0.1` is causing a build failure on android with the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.facebook.flipper.BuildConfig found in modules jetified-flipper-0.75.1-runtime (com.facebook.flipper:flipper:0.75.1) and jetified-flipper-noop-0.138.0-runtime (com.facebook.flipper:flipper-noop:0.138.0)
     Duplicate class com.facebook.flipper.android.AndroidFlipperClient found in modules jetified-flipper-0.75.1-runtime (com.facebook.flipper:flipper:0.75.1) and jetified-flipper-noop-0.138.0-runtime (com.facebook.flipper:flipper-noop:0.138.0)
     Duplicate class com.facebook.flipper.android.diagnostics.FlipperDiagnosticActivity found in modules jetified-flipper-0.75.1-runtime (com.facebook.flipper:flipper:0.75.1) and jetified-flipper-noop-0.138.0-runtime (com.facebook.flipper:flipper-noop:0.138.0)
     Duplicate class com.facebook.flipper.core.FlipperClient found in modules jetified-flipper-0.75.1-runtime (com.facebook.flipper:flipper:0.75.1) and jetified-flipper-noop-0.138.0-runtime (com.facebook.flipper:flipper-noop:0.138.0)
     Duplicate class com.facebook.flipper.core.FlipperPlugin found in modules jetified-flipper-0.75.1-runtime (com.facebook.flipper:flipper:0.75.1) and jetified-flipper-noop-0.138.0-runtime (com.facebook.flipper:flipper-noop:0.138.0)

```

**Comment by jason-vault** [comment]
@niamh-coleman I'm experiencing the same issue as @armouti. Seems to derive from the Android SDK. Specifically version `12.1.1` includes Flipper in both feature and debug configurations while `12.0.0` does not.

```
    \--- io.intercom.android:intercom-sdk:12.1.1
|         +--- io.intercom.android:intercom-sdk-base:12.1.1
|         |    +--- org.jetbrains.kotlin:kotlin-parcelize-runtime:1.6.10
|         |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.6.10 (*)
|         |    |    \--- org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.6.10
|         |    |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.6.10 (*)
|         |    +--- com.facebook.flipper:flipper-noop:0.138.0
|         |    |    \--- com.google.code.findbugs:jsr305:3.0.2
```

**Comment by levynir** [comment]
Hi there. Version 3.0.1 with SDK 12.1.1 does not compile with the same error @armouti reported. Downgrading to 3.0.0 solves the issue. Too me the better part of the day to figure out this was not my fault.

**Comment by prithivraj** [comment]
@levynir @jason-vault @armouti 
I've now released v3.0.3 that should fix this issue. Please upgrade let me know if the problem persists.
Thanks!

**Comment by levynir** [comment]
I can confirm that 3.0.3 was built successfully. Thanks!

**Pull request merged**
