### PR TITLE
Release 3.0.0

### PR DESCRIPTION
**Pull request by kbrdthenerd**
### 🚀 Enhancements

**Introducing Intercom Surveys — beautiful native in-product surveys to bring all your customer communication to one platform!!**

Intercom Surveys Introduction

**📱 New feature: Intercom Surveys**

👋🏼  Meet Intercom Surveys - Don’t just ask their opinion, act on it. Now, you can seamlessly capture and act on customer feedback and needs, all within Intercom. Intercom Surveys makes it quick and easy to create and send highly targeted, easily customisable in-product native survey - across web and mobile. 

* Choose the relevant question type from multitude of question types available like rating scales (NPS, emoji, star), multiple-choice, dropdown and more
* Customise the color of your survey’s background and buttons 
* Target the right survey to the right audience at the right time
* Save survey responses as user attributes to drive follow up actions 
* Add a customisable intro and thank you message
* Decide whether or not users should be able to dismiss the survey
* Encourage further user actions by inserting a call-to-action button in the thank you message with a link (external URL or deep link)
* Leverage email and mobile push as fallback channels if in-product doesn’t get you a response
* Many more ways to customise your survey — show or hide avatar of survey sender, format survey text and insert user or company attributes in text
* Use the power of Intercom platform — A/B testing and control groups, goal tracking, orchestrating surveys as a part of series, analysing and exporting results as CSV

| | |
| ------------- | ------------- |
| surveys gif 1 | surveys gif 2 |

👉  You will need to start a 14 day free trial or purchase the Surveys Add-On starting from $49 per month in order to set a survey live 
👉  Upgrade to the latest version of the mobile SDK today to use the feature on mobile. No additional integration work required.

[Learn more about Intercom Surveys](https://www.intercom.com/surveys) 

https://user-images.githubusercontent.com/3718984/159649798-a255ab7a-df79-4015-875c-399872e6186c.mp4

https://user-images.githubusercontent.com/6392766/159682983-e13d3080-8025-4f90-9a75-14f41b81a5bc.mp4

### CODE REVIEW

**Comment by EmilScherdin** [comment]
This is perfect, been waiting for the survey support, thank you! @kbrdthenerd 

One question; is there an API for presenting a survey already added, I can't seem to find it and looking at the Intercom website on how to display it, it only shows the native way to do it. 

Thinking of something like the carousel display function. Is there something like that for surveys?

**Comment by jason-vault** [comment]
@niamh-coleman @prithivraj @kbrdthenerd  

On mobile, are surveys supposed to trigger automatically much like Carousels? We are seeing a behavior on both Android and iOS (version 3.0.3) where Surveys only trigger after a force close of the app, and not upon the triggering event being received by Intercom. We have tried multiple configurations to have them trigger immediately, but they just don't.

Somewhat unrelated: it would be great to have issues turned on for your Github repositories.

**Comment by MorenoMdz** [comment]
> @niamh-coleman @prithivraj @kbrdthenerd
> 
> On mobile, are surveys supposed to trigger automatically much like Carousels? We are seeing a behavior on both Android and iOS (version 3.0.3) where Surveys only trigger after a force close of the app, and not upon the triggering event being received by Intercom. We have tried multiple configurations to have them trigger immediately, but they just don't.
> 
> Somewhat unrelated: it would be great to have issues turned on for your Github repositories.

image

Do your carousels actually trigger automatically? I can only get ours to show programmatically O.o

**Comment by burzacoding** [comment]
Please open the issues

**Comment by prithivraj** [comment]
Folks, please use the messenger on intercom.com to get product support. We're only a chat message away. 

We deliberately closed off issues on this repository as it was difficult for us to talk to customers on a public platform because debugging issues often involve sharing or talking about customer data.

**Comment by MorenoMdz** [comment]
> Folks, please use the messenger on intercom.com to get product support. We're only a chat message away.
> 
> We deliberately closed off issues on this repository as it was difficult for us to talk to customers on a public platform because debugging issues often involve sharing or talking about customer data.

Hey @prithivraj , thanks for the response, sadly I did not have a good experience getting responses from the intercom messages, asking about specific details that were not in the documentation. Having a dedicated ticketing system might be ideal IMHO.

**Pull request merged**
