### PR TITLE
Android: Allow specifying firebase messaging version

### PR DESCRIPTION
**Pull request by stigi**
Using this package together with the popular `react-native-push-notification` package currently clashes when it comes to the firebase version in use. `react-native-push-notifications` defaults to version 21.1.0 and can't be downgraded to 20.2.+ because of it's use of the `getToken` API.

I propose allowing to set the `firebaseMessagingVersion` as is done in the other library as well: [see their docs](https://github.com/zo0r/react-native-push-notification#android-manual-installation).

### CODE REVIEW

**Comment by dmackinn** [comment]
@niamh-coleman any chance this could get reviewed/merged?

**Comment by idrissakhi** [comment]
should be approved, to ease sdk integration

**Comment by dmackinn** [comment]
@bboyle18 can you review? This PR has been open for a year now. A lot of people use both packages together and this small refactor would ease resolving these library conflicts.

**Review by prithivraj — DISMISSED** [review]

**Comment by stigi** [comment]
Thanks @prithivraj 🙌

**Pull request merged**
