### PR TITLE
fix package.json types entry

### PR DESCRIPTION
**Pull request by ottob**
When I installed the package the typescript definition ended up in:

node_modules/@intercom/intercom-react-native/lib/typescript/src/index.d.ts

not sure if this is the correct fix or of the build can instead put the types file in the typescript folder without the src folder.

### CODE REVIEW

**Comment by lodev09** [comment]
Someone merge this lol.. types is broken on `6.5.0`

**Comment by filipef101** [comment]
Wild.. Intercom has been a rollercoaster..

**Review by KarlosQ — APPROVED** [review]

**Comment by uen** [comment]
I am shocked this made it to a release..

**Comment by Daniel-Griffiths** [comment]
> Wild.. Intercom has been a rollercoaster..

Get me off this wild ride 😭

**Comment by vomchik** [comment]
+1

**Review by liutingdu — APPROVED** [review]

**Review by TNAJanssen — APPROVED** [review]

**Comment by TNAJanssen** [comment]
@IAmConorNolan

**Comment by uddish** [comment]
Hey everyone 👋 
Apologies for the delay here.
We introduced a change in version 6.5.0 which had a side impact on typescript imports, thus causing this issue.
I want to reassure you that we've taken action to address this promptly. I've merged the necessary changes, and we'll soon be releasing a new version of React Native to rectify this issue.

Thank you all for your patience and understanding as we work through this.

**Pull request merged**
