### PR TITLE
[IGNORE THIS] This PR should automatically appear on Messenger Oncall board

### PR DESCRIPTION
**Pull request by trousev**
Subj. Just testing workflows and all this.

### CODE REVIEW

**Comment by trousev** [comment]
Successfully appeared. Closing PR.

**Comment by trousev** [comment]
We'll need more fun for lifecycle. Reopening.

**Review by rathesDot — CHANGES_REQUESTED** [review]
Testing

**Review by rathesDot — APPROVED** [review]

**Comment by trousev** [comment]
Everything works as expected. Closing PR.

**Pull request closed without merging**
